# Generated by Django 4.1.13 on 2025-06-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIB', 'Produto Interno Bruto'), ('IPCA', 'Inflação IPCA'), ('CAMBIO', 'Câmbio'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor', models.FloatField()),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
